### ISSUE TITLE
Component: List

### ISSUE THREAD

**Issue by haydn** [katalyst/ornament#10]
```scss
.list-numbered {
  list-style-type: decimal;
  padding-left: $list-padding;
}
.list-bulleted {
  list-style-type: disc;
  padding-left: $list-padding;
}
.list-inline {
  li {
    display: inline;
  }
}
.list-inline-block {
  li {
    @include inline-block;
  }
}
```
